### ISSUE TITLE
I'm stuck in part 5

### ISSUE THREAD

**Issue by FifineHex** [getnamo/socketio-client-prebuild#8]
is it possible to further specify part 5? I still do not understand what files I have to copy (sorry, I'm a beginner in the boost).

I've already tried copying the files from the boost/boost folder into src/socketio..../boost and also separating the two folders and only linking but without success, if you can do a more detailed explanation of what to do in that part, a lot thanks <3

**Comment by getnamo** [comment]
I've changed to a version that doesn't require boost: https://github.com/getnamo/socket.io-client-cpp/tree/f370a4579773020986b54866b040099e7069a50b. You should be able to just use that branch and use cmake to generate the project files without needing additional steps.

If you do want to specifically use this prebuild, download from e.g. https://www.boost.org/users/download/ and move the 'boost' folder from the zip into ```{this dir}/src/socket.io-client-cpp/boost``` such that the include folder is ```{this dir}/src/socket.io-client-cpp/boost/boost```

**Comment by FifineHex** [comment]
thank you very much, I was getting very frustrated not being able to use with the lib boost, now I got to use it and it will help me in many in the running of my game, aaaaaaaaa I'm very happy
