### ISSUE TITLE
How to deal for step 9 & module machine type 'X86' conflicts with target machine type 'x64'?

### ISSUE THREAD

**Issue by chenqihui** [getnamo/socketio-client-prebuild#9]
hello,

I understand the step 9:
"Remove Additional build settings for x64 platform (so that you don't get target machine mismatch error)"
And I don't find it in VS2017(Could you give way?)

When I try build .sln, it fail:
"fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'"

thank you

**Comment by getnamo** [comment]
These days I'd probably recommend using the non-boost include-only version of the third party dependencies which would allow you to skip library compilation. See https://github.com/getnamo/socket.io-client-cpp/tree/non-boost, and e.g. https://github.com/getnamo/socketio-client-ue4/tree/master/Source/ThirdParty and https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOLib/SocketIOLib.Build.cs#L32 for architecture and guidance. 

That said, if you want to still use this library approach, you'd go into your project setting and change e.g. preprocessor definitions from

![image](https://user-images.githubusercontent.com/542365/68349606-9871e080-00b2-11ea-8e88-90c43201b973.png)

to 

![image](https://user-images.githubusercontent.com/542365/68349615-a1fb4880-00b2-11ea-9027-e79144d3b5b8.png)

and go through any other settings in the sioclient.vcxproj that have 32bit settings still set for x64.

**Comment by chenqihui** [comment]
Got that.
I mark down and try it later. 
Thank you ^_^
